package models

import (
	"strings"
	"time"

	"github.com/lib/pq"
)

// Match represents a job-employee match generated by the AI
type Match struct {
	ID          string    `json:"id" gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	JobID       string    `json:"job_id" gorm:"type:uuid;not null;index"`
	EmployeeID  string    `json:"employee_id" gorm:"type:uuid;not null;index"`
	
	// Match scores (0-100)
	OverallScore    int     `json:"overall_score" gorm:"not null"`
	SkillsScore     int     `json:"skills_score"`
	ExperienceScore int     `json:"experience_score"`
	LocationScore   int     `json:"location_score"`
	SalaryScore     int     `json:"salary_score"`
	CultureScore    int     `json:"culture_score"` // Based on GitHub activity/company values
	
	// Detailed breakdown
	MatchingSkills      pq.StringArray `json:"matching_skills" gorm:"type:text[]"`
	MissingSkills       pq.StringArray `json:"missing_skills" gorm:"type:text[]"`
	MatchingExperience  pq.StringArray `json:"matching_experience" gorm:"type:text[]"`
	
	// AI-generated insights
	MatchReason     string  `json:"match_reason" gorm:"type:text"`
	ImprovementTips string  `json:"improvement_tips" gorm:"type:text"`
	InterviewTips   string  `json:"interview_tips" gorm:"type:text"`
	
	// Status
	IsViewed        bool      `json:"is_viewed" gorm:"default:false"`
	IsApplied       bool      `json:"is_applied" gorm:"default:false"` // Whether employee applied
	EmployerInterest int      `json:"employer_interest" gorm:"default:0"` // 0-100, employer's interest level
	
	// Timestamps
	CreatedAt       time.Time `json:"created_at" gorm:"autoCreateTime;index"`
	ExpiresAt       time.Time `json:"expires_at" gorm:"index"` // Match expires after 30 days
	
	// Relationships
	Job             *Job             `json:"job,omitempty" gorm:"foreignKey:JobID"`
	Employee        *EmployeeProfile `json:"employee,omitempty" gorm:"foreignKey:EmployeeID"`
}

// MatchFeedback collects user feedback on matches to improve algorithm
type MatchFeedback struct {
	ID          string    `json:"id" gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	MatchID     string    `json:"match_id" gorm:"type:uuid;not null;index"`
	UserType    string    `json:"user_type" gorm:"size:20"` // employee, employer
	Rating      int       `json:"rating"` // 1-5 stars
	WasAccurate bool      `json:"was_accurate"`
	Feedback    string    `json:"feedback" gorm:"type:text"`
	CreatedAt   time.Time `json:"created_at" gorm:"autoCreateTime"`
}

// MatchSettings stores user preferences for matching
type MatchSettings struct {
	ID              string    `json:"id" gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	EmployeeID      string    `json:"employee_id" gorm:"type:uuid;uniqueIndex;not null"`
	
	// Weight preferences (sum to 100)
	SkillsWeight    int       `json:"skills_weight" gorm:"default:40"`
	ExperienceWeight int      `json:"experience_weight" gorm:"default:30"`
	LocationWeight  int       `json:"location_weight" gorm:"default:15"`
	SalaryWeight    int       `json:"salary_weight" gorm:"default:10"`
	CultureWeight   int       `json:"culture_weight" gorm:"default:5"`
	
	// Preference filters
	PreferredLocations []string `json:"preferred_locations" gorm:"type:text[]"`
	PreferredJobTypes  []string `json:"preferred_job_types" gorm:"type:text[]"` // remote, hybrid, onsite
	PreferredEmploymentTypes []string `json:"preferred_employment_types" gorm:"type:text[]"`
	PreferredIndustries []string `json:"preferred_industries" gorm:"type:text[]"`
	
	// Salary expectations (KES)
	MinSalary       int       `json:"min_salary"`
	MaxSalary       int       `json:"max_salary"`
	IsSalaryFlexible bool     `json:"is_salary_flexible" gorm:"default:true"`
	
	// Other preferences
	MaxCommuteMinutes int     `json:"max_commute_minutes" gorm:"default:60"`
	IsOpenToRemote    bool     `json:"is_open_to_remote" gorm:"default:true"`
	IsOpenToRelocate  bool     `json:"is_open_to_relocate" gorm:"default:false"`
	
	// Auto-apply settings
	AutoApplyEnabled   bool      `json:"auto_apply_enabled" gorm:"default:false"`
	AutoApplyThreshold int       `json:"auto_apply_threshold" gorm:"default:85"` // Only auto-apply to matches above this score
	NotificationEnabled bool     `json:"notification_enabled" gorm:"default:true"`
	
	UpdatedAt       time.Time `json:"updated_at" gorm:"autoUpdateTime"`
	
	// Relationship
	Employee        *EmployeeProfile `json:"employee,omitempty" gorm:"foreignKey:EmployeeID"`
}


// SearchHistory tracks what users search for (improves recommendations)
type SearchHistory struct {
	ID          string    `json:"id" gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	UserID      string    `json:"user_id" gorm:"type:uuid;not null;index"`
	UserType    string    `json:"user_type" gorm:"size:20"` // employee, employer
	SearchQuery string    `json:"search_query" gorm:"type:text"`
	Filters     JSONMap   `json:"filters" gorm:"type:jsonb"`
	ResultsCount int      `json:"results_count"`
	SearchedAt  time.Time `json:"searched_at" gorm:"autoCreateTime;index"`
}

// TableName specifies table names
func (Match) TableName() string {
	return "matches"
}

func (MatchFeedback) TableName() string {
	return "match_feedback"
}

func (MatchSettings) TableName() string {
	return "match_settings"
}

func (SearchHistory) TableName() string {
	return "search_history"
}

// Helper methods for Match
func (m *Match) GetScoreCategory() string {
	if m.OverallScore >= 85 {
		return "Excellent Match 🎯"
	} else if m.OverallScore >= 70 {
		return "Strong Match 👍"
	} else if m.OverallScore >= 50 {
		return "Potential Match 🤔"
	} else {
		return "Low Match 👎"
	}
}

func (m *Match) GetScoreColor() string {
	if m.OverallScore >= 85 {
		return "green"
	} else if m.OverallScore >= 70 {
		return "blue"
	} else if m.OverallScore >= 50 {
		return "yellow"
	} else {
		return "red"
	}
}

func (m *Match) HasMissingSkills() bool {
	return len(m.MissingSkills) > 0
}

func (m *Match) GetMissingSkillsCount() int {
	return len(m.MissingSkills)
}

// Helper methods for MatchSettings
func (ms *MatchSettings) ValidateWeights() {
	total := ms.SkillsWeight + ms.ExperienceWeight + ms.LocationWeight + ms.SalaryWeight + ms.CultureWeight
	if total != 100 && total > 0 {
		// Normalize to 100
		factor := 100.0 / float64(total)
		ms.SkillsWeight = int(float64(ms.SkillsWeight) * factor)
		ms.ExperienceWeight = int(float64(ms.ExperienceWeight) * factor)
		ms.LocationWeight = int(float64(ms.LocationWeight) * factor)
		ms.SalaryWeight = int(float64(ms.SalaryWeight) * factor)
		ms.CultureWeight = int(float64(ms.CultureWeight) * factor)
	}
}

func (ms *MatchSettings) GetDefaultSettings() *MatchSettings {
	return &MatchSettings{
		SkillsWeight:     40,
		ExperienceWeight: 30,
		LocationWeight:   15,
		SalaryWeight:     10,
		CultureWeight:    5,
		IsOpenToRemote:   true,
		IsSalaryFlexible: true,
		AutoApplyThreshold: 85,
		NotificationEnabled: true,
	}
}

// Scoring algorithm helper
type MatchScoringInput struct {
	Job              *Job
	Employee         *EmployeeProfile
	GithubProfile    *GithubProfile
	EmployeeSkills   []string
	JobRequiredSkills []string
	JobNiceSkills    []string
}

func CalculateSkillMatchScore(employeeSkills, requiredSkills []string) int {
	if len(requiredSkills) == 0 {
		return 100
	}
	
	matchingCount := 0
	employeeSkillSet := make(map[string]bool)
	for _, skill := range employeeSkills {
		employeeSkillSet[normalizeSkill(skill)] = true
	}
	
	for _, reqSkill := range requiredSkills {
		if employeeSkillSet[normalizeSkill(reqSkill)] {
			matchingCount++
		}
	}
	
	return (matchingCount * 100) / len(requiredSkills)
}

func normalizeSkill(skill string) string {
	normalized := strings.ToLower(strings.TrimSpace(skill))

	variations := map[string]string{
		"react.js":     "react",
		"reactjs":      "react",
		"node.js":      "nodejs",
		"nodejs":       "nodejs",
		"postgresql":   "postgres",
		"postgres":     "postgres",
		"typescript":   "typescript",
		"javascript":   "javascript",
		"golang":       "go",
		"golanglang":   "go",
		"kubernetes":   "kubernetes",
		"k8s":          "kubernetes",
		"aws":          "aws",
		"amazon web services": "aws",
		"gcp":          "gcp",
		"google cloud": "gcp",
		"react native": "react native",
		"vue.js":       "vue",
		"vuejs":        "vue",
		"angular.js":   "angular",
		"angularjs":    "angular",
		"express.js":   "express",
		"expressjs":    "express",
	}

	if val, ok := variations[normalized]; ok {
		return val
	}

	suffixes := []string{".js", ".jsx", ".ts", ".tsx", ".py", ".rb", ".go", ".rs"}
	for _, suffix := range suffixes {
		if strings.HasSuffix(normalized, suffix) {
			return strings.TrimSuffix(normalized, suffix)
		}
	}

	return normalized
}

// Batch match results for API responses
type MatchResults struct {
	Total       int      `json:"total"`
	Matches     []*Match `json:"matches"`
	AverageScore int     `json:"average_score"`
	Page        int      `json:"page"`
	Limit       int      `json:"limit"`
	TotalPages  int      `json:"total_pages"`
}